-- YummyPro · Dominios personalizados por negocio
-- Staging migration registrada en Supabase como 20260928061509_business_custom_domains.
-- Producción NO debe recibirla hasta el release coordinado y validado.

create schema if not exists private;

create or replace function private.normalize_custom_hostname(p_hostname text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare v_host text;
begin
  v_host := lower(btrim(coalesce(p_hostname,'')));
  v_host := regexp_replace(v_host, '^https?://', '', 'i');
  v_host := regexp_replace(v_host, '/.*$', '');
  v_host := regexp_replace(v_host, '\\.$', '');
  if v_host = '' or length(v_host) > 253 then raise exception 'Dominio inválido'; end if;
  if v_host !~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$' then
    raise exception 'Dominio inválido';
  end if;
  return v_host;
end $$;

create table if not exists public.business_custom_domains (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  hostname text not null,
  status text not null default 'pending_dns'
    check (status in ('pending_dns','dns_verified','provisioning','active','failed','disabled')),
  verification_token uuid not null default gen_random_uuid(),
  ssl_status text not null default 'pending'
    check (ssl_status in ('pending','initializing','active','error')),
  provider text not null default 'cloudflare_saas',
  provider_hostname_id text,
  verified_at timestamptz,
  activated_at timestamptz,
  last_checked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_custom_domains_hostname_normalized
    check (hostname = lower(hostname) and hostname !~ '[:/\\s]')
);

create unique index if not exists business_custom_domains_hostname_live_uq
  on public.business_custom_domains (lower(hostname)) where status <> 'disabled';
create unique index if not exists business_custom_domains_one_active_uq
  on public.business_custom_domains (restaurant_id) where status = 'active';
create unique index if not exists business_custom_domains_one_pending_uq
  on public.business_custom_domains (restaurant_id)
  where status in ('pending_dns','dns_verified','provisioning');
create index if not exists business_custom_domains_restaurant_idx
  on public.business_custom_domains (restaurant_id,status);

alter table public.business_custom_domains enable row level security;
revoke all on table public.business_custom_domains from anon, authenticated;
grant all on table public.business_custom_domains to service_role;
grant usage,select on sequence public.business_custom_domains_id_seq to service_role;

create or replace function public.get_business_custom_domain(p_restaurant_id bigint)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_active jsonb; v_pending jsonb;
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;
  select jsonb_build_object(
    'hostname',d.hostname,'status',d.status,'ssl_status',d.ssl_status,
    'verified_at',d.verified_at,'activated_at',d.activated_at)
  into v_active from public.business_custom_domains d
  where d.restaurant_id=p_restaurant_id and d.status='active'
  order by d.activated_at desc nulls last,d.id desc limit 1;

  select jsonb_build_object(
    'hostname',d.hostname,'status',d.status,'ssl_status',d.ssl_status,
    'verification_record_name','_yummypro.'||d.hostname,
    'verification_record_value','yummypro-verification='||d.verification_token::text,
    'cname_target','domains.yummypro.online',
    'verified_at',d.verified_at,'last_checked_at',d.last_checked_at,'last_error',d.last_error)
  into v_pending from public.business_custom_domains d
  where d.restaurant_id=p_restaurant_id
    and d.status in ('pending_dns','dns_verified','provisioning','failed')
  order by d.created_at desc,d.id desc limit 1;
  return jsonb_build_object('active',v_active,'pending',v_pending);
end $$;
revoke all on function public.get_business_custom_domain(bigint) from public,anon;
grant execute on function public.get_business_custom_domain(bigint) to authenticated;

create or replace function public.request_business_custom_domain(p_restaurant_id bigint,p_hostname text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_host text;
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;
  if not exists(select 1 from public.restaurants r where r.id=p_restaurant_id and r.active is true) then
    raise exception 'Negocio no disponible';
  end if;
  v_host:=private.normalize_custom_hostname(p_hostname);
  if v_host='yummypro.online' or v_host like '%.yummypro.online'
     or v_host='github.io' or v_host like '%.github.io'
     or v_host='supabase.co' or v_host like '%.supabase.co' then
    raise exception 'Ese dominio está reservado';
  end if;
  if exists(select 1 from public.business_custom_domains d
    where lower(d.hostname)=v_host and d.restaurant_id<>p_restaurant_id and d.status<>'disabled') then
    raise exception 'Ese dominio ya está vinculado a otro negocio';
  end if;
  if exists(select 1 from public.business_custom_domains d
    where d.restaurant_id=p_restaurant_id and lower(d.hostname)=v_host and d.status='active') then
    return public.get_business_custom_domain(p_restaurant_id);
  end if;
  update public.business_custom_domains set status='disabled',updated_at=now()
  where restaurant_id=p_restaurant_id and status in ('pending_dns','dns_verified','provisioning','failed');
  insert into public.business_custom_domains(
    restaurant_id,hostname,status,verification_token,ssl_status,provider,created_at,updated_at)
  values(p_restaurant_id,v_host,'pending_dns',gen_random_uuid(),'pending','cloudflare_saas',now(),now());
  return public.get_business_custom_domain(p_restaurant_id);
exception when unique_violation then raise exception 'Ese dominio ya está en proceso de vinculación';
end $$;
revoke all on function public.request_business_custom_domain(bigint,text) from public,anon;
grant execute on function public.request_business_custom_domain(bigint,text) to authenticated;

create or replace function public.remove_business_custom_domain(p_restaurant_id bigint,p_hostname text default null)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_host text;
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;
  if p_hostname is not null and btrim(p_hostname)<>'' then
    v_host:=private.normalize_custom_hostname(p_hostname);
  end if;
  update public.business_custom_domains set status='disabled',updated_at=now()
  where restaurant_id=p_restaurant_id and status<>'disabled'
    and (v_host is null or lower(hostname)=v_host);
  update public.restaurants r set custom_domain=null,updated_at=now()
  where r.id=p_restaurant_id and (v_host is null or lower(coalesce(r.custom_domain,''))=v_host);
  return public.get_business_custom_domain(p_restaurant_id);
end $$;
revoke all on function public.remove_business_custom_domain(bigint,text) from public,anon;
grant execute on function public.remove_business_custom_domain(bigint,text) to authenticated;

create or replace function public.service_activate_business_custom_domain(
  p_restaurant_id bigint,p_hostname text,p_provider_hostname_id text default null)
returns jsonb language plpgsql security invoker set search_path=''
as $$
declare v_host text;
begin
  v_host:=private.normalize_custom_hostname(p_hostname);
  if not exists(select 1 from public.business_custom_domains d
    where d.restaurant_id=p_restaurant_id and lower(d.hostname)=v_host
      and d.status in ('dns_verified','provisioning','active')) then
    raise exception 'Dominio no verificado';
  end if;
  update public.business_custom_domains set status='disabled',updated_at=now()
  where restaurant_id=p_restaurant_id and status='active' and lower(hostname)<>v_host;
  update public.business_custom_domains
    set status='active',ssl_status='active',
        provider_hostname_id=coalesce(p_provider_hostname_id,provider_hostname_id),
        activated_at=coalesce(activated_at,now()),updated_at=now(),last_error=null
  where restaurant_id=p_restaurant_id and lower(hostname)=v_host;
  update public.restaurants set custom_domain=v_host,updated_at=now() where id=p_restaurant_id;
  return jsonb_build_object('restaurant_id',p_restaurant_id,'hostname',v_host,'status','active');
end $$;
revoke all on function public.service_activate_business_custom_domain(bigint,text,text) from public,anon,authenticated;
grant execute on function public.service_activate_business_custom_domain(bigint,text,text) to service_role;

create or replace function private.enforce_verified_custom_domain()
returns trigger language plpgsql security definer set search_path=''
as $$
declare v_host text;
begin
  if new.custom_domain is not distinct from old.custom_domain then return new; end if;
  if new.custom_domain is null or btrim(new.custom_domain)='' then new.custom_domain:=null; return new; end if;
  v_host:=private.normalize_custom_hostname(new.custom_domain);
  if not exists(select 1 from public.business_custom_domains d
    where d.restaurant_id=new.id and lower(d.hostname)=v_host and d.status='active') then
    raise exception 'El dominio personalizado todavía no está verificado y activo';
  end if;
  new.custom_domain:=v_host;
  return new;
end $$;
drop trigger if exists restaurants_verified_custom_domain_guard on public.restaurants;
create trigger restaurants_verified_custom_domain_guard
before update of custom_domain on public.restaurants
for each row execute function private.enforce_verified_custom_domain();

create or replace function public.streaming_public_catalog(p_ref text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v_business public.restaurants%rowtype;
  v_items jsonb;
  v_ref text:=nullif(lower(btrim(coalesce(p_ref,''))),'');
begin
  select r.* into v_business from public.restaurants r
  where r.active=true and r.business_type='streaming'
    and (lower(r.slug)=v_ref or r.id::text=v_ref or lower(coalesce(r.custom_domain,''))=v_ref
      or lower('www.'||coalesce(r.custom_domain,''))=v_ref)
  limit 1;
  if v_business.id is null then return jsonb_build_object('ok',false,'error','not_found'); end if;
  select coalesce(jsonb_agg(jsonb_build_object(
      'id',p.id,'name',p.name,'duration_days',p.default_duration_days,'price',p.sale_price,
      'available_slots',coalesce(cap.available_slots,0),'active',p.active)
      order by p.sort_order asc,p.name asc),'[]'::jsonb)
  into v_items
  from public.streaming_platforms p
  left join lateral (
    select greatest(coalesce(sum(a.max_slots),0)
      -coalesce(count(s.id) filter(where coalesce(s.status,'active') not in ('cancelled','paused')
        and (s.expires_at is null or s.expires_at>now())),0),0)::int as available_slots
    from public.streaming_accounts a
    left join public.streaming_subscriptions s on s.account_id=a.id and s.restaurant_id=a.restaurant_id
    where a.restaurant_id=v_business.id and a.platform_id=p.id and a.active=true
  ) cap on true
  where p.restaurant_id=v_business.id and p.active=true;
  return jsonb_build_object('ok',true,'business',jsonb_build_object(
    'id',v_business.id,'name',v_business.name,'slug',v_business.slug,
    'whatsapp',coalesce(v_business.whatsapp,''),'currency_code',coalesce(v_business.currency_code,'CLP'),
    'locale',coalesce(v_business.locale,'es-CL'),'country_code',coalesce(v_business.country_code,'CL'),
    'white_label_enabled',coalesce(v_business.white_label_enabled,false)),'items',v_items);
end $$;
